### ISSUE TITLE
[CRUD] Unable to generate the CRUD with an entity mapped with the PHP format

### ISSUE THREAD

**Issue by hhamon** [sensiolabs/SensioGeneratorBundle#1] opened 2011-06-22 08:56 UTC
First, I ran the following command to generate a new Post entity (id, title, content, createdAt, publishedAt)

```
./app/console generate:doctrine:entity --entity=AcmeBlogBundle:Post --format=php
```

The entity has been created under the Entity/Post.php file and its metadata under Resources/config/doctrine/post.orm.php

When I want to generate the CRUD on this entity with the followign command :

```
./app/console generate:doctrine:entity --entity=AcmeBlogBundle:Post --format=yml
```

I get the following error message in the command line :

```
 [Doctrine\ORM\Mapping\MappingException]                                         
 Class Acme\BlogBundle\Entity\Post is not a valid entity or mapped super class.
```

I suppose Doctrine is not able to find metadata in the bundle...

**Comment by ishakuta** [comment] 2015-01-09 17:21
actually it's because it 2.3.4 version of sensio generator bundle there was used wrong MetadataFactory:
https://github.com/sensiolabs/SensioGeneratorBundle/blob/v2.3.4/Command/GenerateDoctrineCommand.php#L36
that used for existing entities, but our target entity not yet generated, so in 2.3.5 they already fixed this:
https://github.com/sensiolabs/SensioGeneratorBundle/blob/v2.3.4/Command/GenerateDoctrineCommand.php#L36
using DisconnectedMetadataFactory

**Comment by javiereguiluz** [comment] 2015-07-16 14:19
I can confirm that this bug still exists. Anyone is willing to work on fixing this 4-years-old issue? If not, can someone please explain me in detail the needed changes to solve this? Thanks.

**Comment by aapis** [comment] 2015-12-11 21:32
I'm also experiencing this problem still.  Created an entity from an existing database schema, ran this command to create CRUD for it, but it errors out and asks for a --path arg, then says --path doesn't exist as an option.  Going to work around it by manually creating the files.

**Comment by fabpot** [comment] 2020-01-06 12:25
Closing this issue as this bundle is now obsolete. Please, use the maker bundle instead.

**Closed by fabpot** 2020-01-06 12:25 UTC
Labels: Bug
