### ISSUE TITLE
Generated bundle are not autoloaded

### ISSUE THREAD

**Issue by Nicosonic** [sensiolabs/SensioGeneratorBundle#555] opened 2017-07-06 13:49 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | >= 3.3.3

When generating a bundle with `bin/console generate:bundle`  the bundle is not autoloaded automatically anymore. It gives the following error when trying to load a page :

> Attempted to load class "NameBundle" from namespace "NameBundle".
Did you forget a "use" statement for another namespace?

This used to worked in previous versions. At least for the 3.2.*

To get it works on 3.3*, I used this workaround in the composer.json : 
```
"psr-4": {
        "AppBundle\\": "src/AppBundle",
        "NameBundle\\": "src/NameBundle"
},
```

And played this command on the server : 
```composer dump-autoload```

**Comment by bennukem** [comment] 2017-07-06 13:54
To avoid to manipulate for each bundle.
```
"psr-4": {
        "": "src/"
},
```

**Comment by Pierstoval** [comment] 2017-07-11 17:44
What you are doing is not a workaround, this is the expected behavior.

Using @bennukem's proposal `"": "src/"` in PSR-4 section leads to autoload performance issues. It was fixed in symfony/symfony-demo#490 and symfony/symfony-standard#1048 and it's Flex default behavior too, whereas Flex has a much more comfortable way of doing it because `src/` corresponds to the `App` namespace, which avoids having to declare multiple namespaces in `src/`

**Comment by Nicosonic** [comment] 2017-07-11 18:34
Ok. I understand what you're saying. But the documentation never mentionned something like that. As a standard user, I can not guess this behavior. 

I think the documentation should be updated or at least the last output of the command should mentionned this instead of the "let's get to work" message.

**Comment by javiereguiluz** [comment] 2017-07-11 18:38
@Nicosonic I'm sorry for your bad experience. You are right. Sadly this bundle is not getting the attention it deserves. Moreover, the changes introduced by recent Symfony versions and the changes proposed for the next Symfony 4 version, makes it hard to be compatible with every possible Symfony use.

I can't promise a specific date, but improving this bundle **A LOT** is high in our TODO list.

**Comment by Nicosonic** [comment] 2017-07-11 18:45
What if I try to update the last message of the command and make a PR for this ? Is there a chance to be merged ?

**Comment by Pierstoval** [comment] 2017-07-11 18:48
@Nicosonic It's a solution, but for this you must check whether the class is autoloadable before showing a message, else it becomes a bit useless to warn the user about an issue he might not have. But feel free to make a PR 😉.

**Comment by guilliamxavier** [comment] 2017-07-12 14:33
Related PRs: #557 (documentation), #559 (re-report errors)

**Closed** 2017-07-12 17:23 UTC
Labels: Feature
