### ISSUE TITLE
Is there a way to generate forms from entities declared outside of a bundle ?

### ISSUE THREAD

**Issue by paztek** [sensiolabs/SensioGeneratorBundle#323] opened 2014-12-09 17:47 UTC
I declared my model outside of my bundles under the Paztek\Entity namespace and now I'm trying to generate a FormType for one of my entities.

Here is my mapping in my ```config.yml```file:
```
doctrine:
    ...
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
                paztek:
                        type: annotation
                        is_bundle: false
                        dir: %kernel.root_dir%/../src/Paztek/Entity
                        alias: "core"
                        prefix: Paztek\Entity

```
The command ```doctrine:generate:form core:MyEntity``` fails with:
```
Bundle "core" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file?
```

I tried omitting the "core", giving the fully qualified name of my entity, etc... but this is the closest I can get.

Any idea if this is possible at all and how to do it ?

**Comment by austinh** [comment] 2015-02-03 04:03
+1 I am also having this problem. Very frustrating.

**Comment by javiereguiluz** [comment] 2015-07-17 18:29
I'm closing it as duplicate of #335 (the latter PR si more recent, but includes a better discussion about this issue).

**Closed by javiereguiluz** 2015-07-17 18:29 UTC
Labels: Feature
