### ISSUE TITLE
doctrine:generate:crud with xml generates routing.yml

### ISSUE THREAD

**Issue by hdramos** [sensiolabs/SensioGeneratorBundle#225] opened 2013-09-01 06:39 UTC
doctrine:generate:crud with the xml option generates 

```
Resources/config/routing.yml
```  
This happens even if Resources/config/routing.xml exists. 

Resources/config/routing/routing/entity.xml is generated properly.

Using 2.3. Bundle generated using generate:bundle with option xml.

**Comment by javiereguiluz** [comment] 2015-07-17 15:40
I confirm this bug. Hwoever, I'm closing this issue as duplicate of #225. I know that this issue was reported earlier, but the latter includes a discussion and a linked pull request to solve the issue. Thanks.

**Closed by javiereguiluz** 2015-07-17 15:40 UTC
Labels: Bug

**Comment by xabbuh** [comment] 2015-07-17 21:46
@javiereguiluz This **is** #255. :) Which issue did you think of?

**Comment by javiereguiluz** [comment] 2015-07-18 09:43
@xabbuh sorry! I was referring to #244.

**Comment by xabbuh** [comment] 2015-07-19 12:54
@javiereguiluz thanks
