### ISSUE TITLE
In windows 10, displays error after generating new bundle from command line

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioGeneratorBundle#563] opened 2017-07-16 10:07 UTC
Copied from https://github.com/symfony/symfony/issues/23504

-----

ClassNotFoundExceptionAttempted to load class "TestBundle" from namespace "TestBundle".Did you forget a "use" statement for "Symfony\Bundle\FrameworkBundle\Tests\Functional\Bundle\TestBundle\TestBundle"?

in AppKernel.php (line 19)

**Comment by xabbuh** [comment] 2017-07-17 06:55
Duplicate of #555 and #558?

**Closed** 2017-07-18 09:09 UTC
