### ISSUE TITLE
Doctrine:generate:entity "NOTICE ERROR"

### ISSUE THREAD

**Issue by a289459798** [sensiolabs/SensioGeneratorBundle#189] opened 2013-04-19 01:12 UTC
sudo php app/console doctrine:generate:entity --entity="AcmeDemoBundle:User" --fields="username:string(100) password:string(32) login_time:integer total:integer"

Notice: Undefined variable: output in /opt/case/symfony/Symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/DialogHelper.php line 411

why?

**Comment by phansys** [comment] 2015-07-03 12:36
@a289459798, I know this one is pretty old, but can you tell the version you're using and paste a full exception stack?

**Comment by javiereguiluz** [comment] 2015-07-17 15:28
I'm closing it as "fixed" because I can't reproduce this issue in any way. If you have more information about the error, please reopen this issue. Thanks.

**Closed by javiereguiluz** 2015-07-17 15:28 UTC
Labels: Bug
