### ISSUE TITLE
2.3 put the twig file in src dir but 3.0 in app?

### ISSUE THREAD

**Issue by xxfaxy** [sensiolabs/SensioGeneratorBundle#466] opened 2016-02-01 01:57 UTC
It's a bug?

**Comment by xabbuh** [comment] 2016-02-01 11:10
Generating templates in the `app/Resources/views` directory was done to follow the [best practices](http://symfony.com/doc/current/best_practices/templates.html#template-locations).

**Comment by javiereguiluz** [comment] 2016-02-09 14:12
@xxfaxy thanks for reporting this change. However, as @xabbuh said, this is intended a not a bug, so I'm closing this issue.

**Closed by javiereguiluz** 2016-02-09 14:12 UTC
