### ISSUE TITLE
console does not recognize entity "alias"

### ISSUE THREAD

**Issue by nimasdj** [sensiolabs/SensioGeneratorBundle#326] opened 2015-01-09 15:43 UTC
I use /app/config/config.yml to setup doctrine. I set is_bundle to false and set a namespace with "prefix" and set location with "dir" then I generate CRUD. Until here everything is fine but I get console error when I want to set "alias" too.
But if I generate CRUD without "alias" and add "alias" after crud generation and apply changes in my crud controller it recognizes my alias and works fine. It seems console does not recognize "alias". Isn't it a bug?

**Comment by garak** [comment] 2015-03-18 08:25
Looks like a duplicate of #277

**Comment by javiereguiluz** [comment] 2015-07-17 11:01
Closing it as a duplicate of #277. Thanks @garak.

**Closed by javiereguiluz** 2015-07-17 11:01 UTC
