### ISSUE TITLE
Proposal - Multiple skeleton choise

### ISSUE THREAD

**Issue by nykopol** [sensiolabs/SensioGeneratorBundle#265] opened 2014-03-19 13:21 UTC
I'm actually facing a problem. As i don't have the same template for front and admin, i would like to have 2 skeletons for CRUD generator. 

The problem is that i don't know how to select witch one must be used. Tell me if i'm wrong, but the solution of overwrite with something like `BUNDLE_PATH/Resources/SensioGeneratorBundle/skeleton/crud` is not good for me as it restrict the use of 1 skeleton by bundle. And what if we want to use the skeleton of bundle A in bundle B?

I think it would be more flexible to use something like an option `--skeleton-path`.

Is there an other solution that respond to my problem without modification of this bundle ?

**Comment by javiereguiluz** [comment] 2015-08-10 08:58
Closing it as "won't fix". The current simple skeleton overriding feature is enough for now. There are other issues and pull requests to improve this inheritance mechanism, so this issue can also be considered as a more generic duplicate of them. In any case, thanks for proposing this improvement!

**Closed by javiereguiluz** 2015-08-10 08:58 UTC
Labels: Feature, won't fix
