### ISSUE TITLE
Strange Behavior - potential bug that prevent skeleton overriding

### ISSUE THREAD

**Issue by SulivanDotEu** [sensiolabs/SensioGeneratorBundle#266] opened 2014-03-20 11:33 UTC
Hi everybody!

I have a lot of truble to inherit the SensioGeneratorBundle. I'm trying to inherit the Constructor generated by the DoctrineCrudGenerator.php.
For that, I have:
- created a new bundle "WalvaCrudGeneratorBundle" in which I specifed in the Bundle class : getParent = SensioGeneratorBundle
- put it in the appKernel just after SensioGeneratorBundle
- created a class "AdvancedCrudCommand" that extends GenerateDoctrineCrudCommand in with I simply overwride the method configure.
- created some new skeleton in MyBundle/Ressources/SensioGeneratorBundle/skeleton/crud/actions/[create.php.twig....update.php.twig]
- (I olso tried to put then in MyBundle/Ressources/skeleton/crud/actions/[create.php.twig....update.php.twig])

I oslo tried this manual : http://symfony.com/doc/current/bundles/SensioGeneratorBundle/index.html

And I didn't figure out why my command still not override your skeleton/templates.

So I did some research in your code and there is something I don't understand: 
In the class Sensio\Bundle\GeneratorBundle\Command\GeneratorCommand, there is a method that give the SkeletonDirs (line 46).
It try to include "$dir = $bundle->getPath().'/Resources/SensioGeneratorBundle/skeleton')". So I tested the var if it was pointing to the my skeleton directories.
To do that, I run my command.
myCommand:generate:crud
with these param: --entity="WalvaVideoBundle:Source" --with-write --format="yml" --overwrite --route-prefix="video_source"
The $dir gaves me: string(88) "C:\wamp\www\MY_APP\src\Walva\VideoBundle/Resources/SensioGeneratorBundle/skeleton". Which refer to the command param *--entity*
Is these behavior correct? 

Some people on internet (mainly on stackoverflow) wonder why the inheritance works when new skeletons are in the APP_PATH and not in the BUNDLE_PATH. (cfr official doc)

I might say lot's of crap, sorry if it is the case :D
If I am right, I'll learn how to fork and pull request ;)
Thank you in advance.
Benjamin E.

PS: This is my first issue report ever, sorry for eventual mistakes.

**Comment by HeahDude** [comment] 2016-10-08 14:07
Hi @SulivanDotEu! It looks like some time has passed since you opened your first issue :)

No need to extend the bundle to have your own commands, just make sure, as you noticed, that your command extends the base `GeneratorCommand` class and you'll be able to override how to find templates (see https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Command/GeneratorCommand.php#L46).

Since this issue is quite old now and no one seems to have confirmed it, I'm closing.

Feel free to comment if you still encounter this problem in version 3.0 of the bundle, the only maintained version now, and we'll reopen. Thanks!

**Closed by HeahDude** 2016-10-08 14:07 UTC
Labels: Bug

**Comment by SulivanDotEu** [comment] 2016-10-10 08:03
Thanks for the answer, I confirm the last release fix my problem

**Comment by HeahDude** [comment] 2016-10-10 08:18
Cool, thanks for the update :)
