### ISSUE TITLE
Symfony 3.4: generated Controller actions and  templates result in: Error Unable to find template

### ISSUE THREAD

**Issue by lbm-services** [sensiolabs/SensioGeneratorBundle#588] opened 2017-12-15 21:58 UTC
Namespacing paths has changed since [Symfony 3.4.](https://symfony.com/doc/3.4/templating/namespaced_paths.html)

So the same issue appears after updating Symfony 3.3 applications to 3.4.
```
public function indexAction()
    {
        return $this->render('AppBundle:Blog:index.html.twig', array(
            // ...
        ));
    }
```
Since I have chosen annotions the resulting controller file should look like this:

```
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

 /**
     * @Route("/blog")
     */
class BlogController extends Controller
{
    /**
     * @Route("/index")
     * @Template("@App/Blog/index.html.twig")
     */
    public function indexAction()
    {
    }

```
After changing the first line in the twig templates:
`{% extends "::base.html.twig" %}`

to

`{% extends "base.html.twig" %}`

Everything works fine again.

**Comment by fabpot** [comment] 2017-12-16 00:28
duplicate of #587

**Closed by fabpot** 2017-12-16 00:28 UTC
