### ISSUE TITLE
generate:entity throws mkdir(): File exists

### ISSUE THREAD

**Issue by mountain-code** [sensiolabs/SensioGeneratorBundle#524] opened 2016-11-07 15:07 UTC
After updating sensio/generator-bundle from version **3.0.11** to **3.1.0** on Windows 10 I get an error every time I try to create a new entity via doctrine:generate:enity

[Symfony\Component\Debug\Exception\ContextErrorException]
Warning: mkdir(): File exists

`Exception trace:
 () at C:\wamp64\www\project\vendor\sensio\generator-bundle\Generator\Generator.php:75
 Symfony\Component\Debug\ErrorHandler->handleError() at n/a:n/a
 mkdir() at C:\wamp64\www\project\vendor\sensio\generator-bundle\Generator\Generator.php:75
 Sensio\Bundle\GeneratorBundle\Generator\Generator::mkdir() at C:\wamp64\www\project\vendor\sensio\generator-bundle\Generator\DoctrineEntityGenerator.php:99
`

Switching back to 3.0.11 solves the problem. Any suggestions?

Thanks.

**Comment by HeahDude** [comment] 2016-11-07 15:18
Hi @mountain-code thank you for reporting this issue, we'll try to provide a fix shortly. I'm closing here as duplicate of #523 which open just a few minutes before.

**Closed by HeahDude** 2016-11-07 15:18 UTC
Labels: Bug
