### ISSUE TITLE
Controller generator doesn't work with the latest best practices

### ISSUE THREAD

**Issue by parhamdoustdar** [sensiolabs/SensioGeneratorBundle#339] opened 2015-03-25 09:42 UTC
In the best practices document, it's said that:

> Store all your application's templates in app/Resources/views/ directory.

However, the generator seems to infer that I want to share my bundle and put the template in the `Resources/views/` directory of the `AppBundle` bundle.

**Comment by JHGitty** [comment] 2015-05-04 00:15
+1 :+1: 
Relates to https://github.com/sensiolabs/SensioGeneratorBundle/issues/344

**Comment by fabpot** [comment] 2015-06-28 17:37
closing as a duplicate of #344

**Closed by fabpot** 2015-06-28 17:37 UTC

**Comment by jasonroman** [comment] 2017-07-25 14:20
I don't think this issue should be closed.  The current controller generator does not use the Doctrine CRUD Generator to determine template names, and still requires double-colons and still places templates inside the bundle directory, rather than app/Resources/views
